name: Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout submodule FGD
        uses: actions/checkout@v4
        with:
          repository: ./FGD/

      - name: Checkout submodule HammerAddons
        uses: actions/checkout@v4
        with:
          repository: ./HammerAddons/

      - name: Checkout submodule psc-cfg
        uses: actions/checkout@v4
        with:
          repository: ./psc-cfg/
          ssh-key: '${{ secrets.PSCGIT_HAMMER_SSHKEY }}'
          

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-depency-path: 'requirements.txt'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build folder
        run: .\build.bat

      - name: Zip
        uses: TheDoctor0/zip-release@master
        with:
          filename: hammer.zip
          path: ./build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hammer
          path: hammer.zip
        
