name: Release
on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: CheckoutSubmodules
        run: git submodule update --init FGD HammerAddons

      - name: Add SSH permissions
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: "${{ secrets.PSCGIT_HAMMER_SSHKEY }}"

      - name: Add SSH fingerprints
        run: |
          echo '${{ secrets.SSH_RSA_PCS_FINGERPRINT }}' >> $HOME\.ssh\known_hosts
          
      - name: Checkout PSC-CFG
        run: git submodule update --init psc-cfg
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r HammerAddons/requirements.txt
  
      - name: Build folder
        run: .\build.bat

      - name: Clone hammer/ from PCS GIT
        run: git clone -b release --single-branch ssh://git@ssh.project-collapse-studios.org:1206/PCS/hammer.git hammer-release

      - name: Clean repo and upload
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "bot@github.com"
          cd hammer-release
          git rm .
          git revert README.md
          robocopy .\..\build\ .\ /S
          git add .
          git commit -m "Update hammer/"
          git push
        
