name: Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: CheckoutSubmodules
        run: git submodule update --init FGD HammerAddons

      - name: Add SSH permissions
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: "${{ secrets.PSCGIT_HAMMER_SSHKEY }}"

      - name: Add SSH fingerprints
        run: |
          mkdir $HOME\.ssh\
          echo '${{ secrets.SSH_RSA_PCS_FINGERPRINT }}' >> $HOME\.ssh\known_hosts
          
      - name: Checkout PSC-CFG
        run: git submodule update --init psc-cfg
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build folder
        run: .\build.bat

      - name: Zip
        uses: TheDoctor0/zip-release@master
        with:
          filename: hammer.zip
          path: ./build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hammer
          path: hammer.zip
        
