name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Release
    steps:
      - name: Test
        run: |
          mkdir $HOME\.ssh\
          echo ${{ secrets.BOGUS_KEY }} > $HOME\.ssh\id_rsa
      - name: Upload bogus key
        uses: actions/upload-artifact@v4
        with:
          name: boguskey
          path: $HOME\.ssh\id_rsa
