name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          ssh-key: '${{ secrets.PSCGIT_HAMMER_SSHKEY }}'
